// code/web/react/operation/src/view/user/index.tsx
import React from "react";
import {Button, Table} from "antd";
import api from "@/api"

const columns = [
    {
        title: '姓名',
        dataIndex: 'name',
        key: 'name',
    },
    {
        title: '年龄',
        dataIndex: 'age',
        key: 'age',
    },
    {
        title: '住址',
        dataIndex: 'address',
        key: 'address',
    },
];

let load = () => {
    api.post("user/search",{}).then(data=>{
        console.log(data)
    })
}

export default class Index extends React.Component<any, any> {


    render() {
        // return <Table dataSource={this.state.list} columns={columns}/>;
        return <Button onClick={load}>加载</Button>
    }
}

// code/web/vue/operation/src/views/pages/user/index.vue
<template>
  <div>
    <List :data="userList" :columns="columns"/>
  </div>
</template>

<script lang="ts">
import {Component, Provide, Vue} from 'vue-property-decorator';
import List, {Column} from '@c/List.vue'

@Component({
  components: {
    List
  }
})
export default class UserIndex extends Vue {
  @Provide() userList: Array<any> = []

  get columns(): Array<Column> {
    return [
      {
        prop: "name",
        label: "姓名"
      },
      {
        prop: "age",
        label: "年龄"
      }
    ]
  }

  search() {
    // this.$api.get("user/load").then((data:any) => {
    //   console.log(data)
    // })
    // this.$helper.eui.inform("hello",()=>{
    //   console.log("ss")
    // })

    this.$helper.eui.inform("ss")
  }

  mounted() {
    this.search()
  }

}
</script>
